[env]
ADDRESS = "127.0.0.1:7878"
MAX_THREADS = "6"
MAX_BUF_SIZE = "1024"
STREAM_READ_TIMEOUT = "100"
STREAM_WRITE_TIMEOUT = "100"
PUBLIC_DIR = "examples/public"
COMPILE_TO = "examples/src"
ROOT_FILE = "index"